/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainstrategygame;

import java.awt.Color;
import static java.awt.Color.GREEN;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JButton;
import javax.swing.JPanel;


public class Board extends javax.swing.JFrame {
    
    private static int lastRow = -1;
    private static int lastColumn = -1;
    private static JButton lastClickedButton = null;
    
    private void atualizaInformaçõesLastClickedButton(JButton button) {
        lastClickedButton = button;
        int[] coords = pegaCoordenadas(button);
        lastRow = coords[0];
        lastColumn = coords[1];
    }
    private void atualizaCorBotao(JButton button, Color cor) {
        button.setBackground(cor);
        if (lastClickedButton != null && !lastClickedButton.equals(button)) {
            lastClickedButton.setBackground(null);
        }
        lastClickedButton = button;
    }
    private int[] pegaCoordenadas(JButton buttonClicked) {
        Container parent = buttonClicked.getParent();
        GridBagLayout gridBagLayout = (GridBagLayout) parent.getLayout();
        GridBagConstraints constraints = gridBagLayout.getConstraints(buttonClicked);
        int row = constraints.gridy;
        int column = constraints.gridx;
        return new int[] {row, column};
    }
    private int calculoDistância (JButton botãoSelecionado, JButton botãoASelecionar){
        int []coordenadaBotãoSelecionado = pegaCoordenadas(botãoSelecionado);
        int []coordenadaBotãoASelecionar = pegaCoordenadas(botãoASelecionar);
        int distância = (coordenadaBotãoSelecionado[0] - coordenadaBotãoASelecionar[0]) + (coordenadaBotãoSelecionado[1] - coordenadaBotãoASelecionar[1]);
        return distância;
    }
    
    public Board() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setName(""); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jButton1, gridBagConstraints);

        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jButton4, gridBagConstraints);

        jButton21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton21.setName(""); // NOI18N
        jButton21.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jButton21, gridBagConstraints);

        jButton22.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton22.setName(""); // NOI18N
        jButton22.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jButton22, gridBagConstraints);

        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.setName(""); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jButton2, gridBagConstraints);

        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton8.setName(""); // NOI18N
        jButton8.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButton8, gridBagConstraints);

        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton9.setName(""); // NOI18N
        jButton9.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButton9, gridBagConstraints);

        jButton12.setText("X");
        jButton12.setEnabled(false);
        jButton12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton12.setName(""); // NOI18N
        jButton12.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButton12, gridBagConstraints);

        jButton23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton23.setName(""); // NOI18N
        jButton23.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton23MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jButton23, gridBagConstraints);

        jButton13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton13.setName(""); // NOI18N
        jButton13.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButton13, gridBagConstraints);

        jButton16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton16.setName(""); // NOI18N
        jButton16.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jButton16, gridBagConstraints);

        jButton17.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton17.setName(""); // NOI18N
        jButton17.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jButton17, gridBagConstraints);

        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.setName(""); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jButton3, gridBagConstraints);

        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.setName(""); // NOI18N
        jButton6.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButton6, gridBagConstraints);

        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.setName(""); // NOI18N
        jButton7.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButton7, gridBagConstraints);

        jButton24.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton24.setName(""); // NOI18N
        jButton24.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton24MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jButton24, gridBagConstraints);

        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.setName(""); // NOI18N
        jButton5.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jButton5, gridBagConstraints);

        jButton11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton11.setName(""); // NOI18N
        jButton11.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButton11, gridBagConstraints);

        jButton14.setText("X");
        jButton14.setEnabled(false);
        jButton14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton14.setName(""); // NOI18N
        jButton14.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButton14, gridBagConstraints);

        jButton18.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton18.setName(""); // NOI18N
        jButton18.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jButton18, gridBagConstraints);

        jButton10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton10.setName(""); // NOI18N
        jButton10.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButton10, gridBagConstraints);

        jButton25.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton25.setName(""); // NOI18N
        jButton25.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton25MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jButton25, gridBagConstraints);

        jButton20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton20.setName(""); // NOI18N
        jButton20.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jButton20, gridBagConstraints);

        jButton15.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton15.setName(""); // NOI18N
        jButton15.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButton15, gridBagConstraints);

        jButton19.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton19.setName(""); // NOI18N
        jButton19.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jButton19, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton19MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton20MouseClicked

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton21MouseClicked

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton22MouseClicked

    private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton23MouseClicked

    private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton24MouseClicked

    private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
        JButton buttonClicked = (JButton) evt.getSource();
        int[] coordinates = pegaCoordenadas(buttonClicked);   int row = coordinates[0];   int column = coordinates[1];
        System.out.println("Linha: " + row + " Coluna: " + column);
        
        atualizaCorBotao(buttonClicked, GREEN);
        if (lastClickedButton != null && !lastClickedButton.equals(buttonClicked)) {
            atualizaCorBotao (lastClickedButton,null);
        }
        lastClickedButton = buttonClicked;
    }//GEN-LAST:event_jButton25MouseClicked

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
